### PR TITLE
Temporarily set moment version to 2.18.1 due to 2.19 instability

### PR DESCRIPTION
**Pull request by bryantwong**
Moment.js is dealing with `./locale` issues (https://github.com/moment/moment/issues/4216), which makes it unusable. For now, can we set the version to 2.18.1, then revert once the issues are fixed?

### CODE REVIEW

**Comment by bryantwong** [comment]
The moment.js guys just pushed a new build (https://github.com/moment/moment/commit/29afed6631e596fe9b3ff6c61ddc55eee18810e6) that seems to solves the `./locale` issues (works locally for me), so this might not be necessary anymore. Want to verify that it works for others first.

**Comment by BrockReece** [comment]
Ah cool, it is good that there is a fix from moment.
However, I think #46 will still be an issue on 2.19.x, I can confirm later this morning

Maybe we could still merge this in to buy us some time to find a fix for that?

**Comment by BrockReece** [comment]
Actually, ignore me. v2.19.1 has fixed issue #46 too.

**Comment by bryantwong** [comment]
I think v2.19.1 is working for almost everyone now, so I'm going to close this PR - if we need it later, we can just reopen it.

**Pull request closed without merging**
