### PR TITLE
support the format of moment filter can use lowercase mode

### PR DESCRIPTION
**Pull request by junfeisu**
支持moment过滤器的format参数能够使用小写模式（support the format of moment filter can use lowercase mode）,eg：
<div>{{someTime | moment('yyyy-mm-dd')}}</div>

### CODE REVIEW

**Comment by junfeisu** [comment]
I know. However, it is very rare to display only MM|mm in the actual situation. In this case, you can add New Date(date).getMonth() + 1, and then make up 0.
Of course, look at your own opinions.
Thanks

**Comment by BrockReece** [comment]
I'm still not sure I understand.

If we convert the format string to uppercase this will be the result
```html
{{someTime | moment('yyyy-mm-dd')}} // 2018-08-07 year-month-day
{{someTime | moment('yyyy-mm-dd hh:mm')}} // 2018-08-07 10:08 year-month-day hour:month
```
The last result displays the month details twice. This isn't the only letter that has different value depending on the case.

**Comment by junfeisu** [comment]
I know what's the problem.I have written a simple similar method:https://github.com/Conjurator/Elegant/blob/master/src/format.js
The method doesn't care single mm|MM. It distinguish the 'mm' is minutes or months with the format in front of or behind 'mm'
But moment care the single mm. So on the upperCase it can not distinguish the mm meaning.
So I owe it to me.

**Comment by brockpetrie** [comment]
I'm personally not a fan of this approach, or any approach where the parsing of formatting tokens 
is changed and requires some implied or explicit additional context. The idea of these parsing tokens is that they are largely exhaustive and can be used in any combination to match any use case.

**Pull request closed without merging**
