### PR TITLE
Remove redundant package and bump package number

### PR DESCRIPTION
**Pull request by BrockReece**
Hi Brock,
We don't need this anymore and now it is causing version issues with moment.

### CODE REVIEW

**Comment by lukpep** [comment]
push it to npm please :)

**Comment by BrockReece** [comment]
@lukpep Will do now

**Comment by BrockReece** [comment]
Done :)

**Comment by lukpep** [comment]
@BrockReece 
unfortunately it didn't help with #7

**Comment by BrockReece** [comment]
@lukpep 
I think that is more of a problem with the code than the npm dependancies.
Do you have any ideas on how to fix it?

**Pull request merged**
