### PR TITLE
Business days

### PR DESCRIPTION
**Pull request by BrockReece**
Nothing special here, just extra cases for manipulating dates based on business days using this [moment plugin] (https://github.com/kalmecak/moment-business-days)

What do you think?

Cheers

### CODE REVIEW

**Comment by brockpetrie** [comment]
Looks good!

We may want to figure out a way to make some of these filtering modalities optional to reduce overhead. Start thinking on how we can best do that. Moment.js alone already has a decent size footprint, so it'd be nice to keep it lean.

In a perfect world, we stop having to explicitly declare filters in our switch case, and just pack up all the filtering arguments and pass them to moment in a sensible way. The problem with that is that some filters have more args than others, so it's tricky to be assumptive with we split the arguments up when chaining. The good part would be that they could use any moment plugin and it'd be plug-and-play.

**Comment by BrockReece** [comment]
Sorry for the delayed response.

How about if I build a way to pass Moment plugins through the Vue plugin options? That will keep our package pretty light and the user can define which plugin they want to use.

**Comment by brockpetrie** [comment]
I really like that idea! That'd be a great solution.

**Comment by BrockReece** [comment]
So the last commit will allow you to load in alternative packages by using...

`Vue.use(require('vue-moment'), {moment: require('moment-business-days')});`

What do you think?

Cheers
Brock

**Comment by brockpetrie** [comment]
Great work!

**Pull request merged**
