### PR TITLE
Npm 

### PR DESCRIPTION
**Pull request by BrockReece**
Hi Brock, 

I have added a package.json file to handle the moment.js dependancy and also wrapped the custom filters in a plugin which should make it super easy to install.

What do you think?
Great name btw :)

Cheers
Brock

### CODE REVIEW

**Comment by brockpetrie** [comment]
Thanks! You may want to consider removing your npm package so I can republish under the original repo to prevent bifurcation.

**Comment by BrockReece** [comment]
I will do, please excuse my impatience.

I am thinking of adding some additional filters for handling business days, would this be of interest to you?

Cheers

**Comment by BrockReece** [comment]
As we have had over 100 downloads since publishing the module on Friday, I don't want to pull the rug out from underneath anyone. I have added you as an owner to the module so you can publish further changes, are you comfortable with that?

**Comment by brockpetrie** [comment]
No worries! :)

Maybe just change the repo on the package to point to the original repo rather than your fork. That should take care of any divergence issues. Thanks again! Keep the PRs coming

Cheers

**Comment by BrockReece** [comment]
Ok, so I have merged the changes, bumped the version and published to NPM.
If I get time I will create a new PR with a couple of new filters in the next couple of days.

Cheers

**Pull request merged**
