### PR TITLE
Update readme.md for 4.0.0

### PR DESCRIPTION
**Pull request by bradyemerson**
Update readme to reflect 4.0.0 changes for passing moment object.

### CODE REVIEW

**Review by BrockReece — COMMENTED** [review]
Isn't this just using the ES2015 object shorthand for property names?

Is this an issue that has been introduced since the release of 4.0.0, because this seems to be more of an issue with the setup of the consuming app?

**Comment by bradyemerson** [comment]
Ah, I bet it was because I didn't call the variable "moment". For me it's "momentTimezone".  However, my previous implementation `Vue.use(VueMoment, {momentTimezone})` worked in 3.x.  In 4.x I had to change to `Vue.use(VueMoment, {moment: momentTimezone})`

**Comment by BrockReece** [comment]
I don't think there was any code in 3.x that accepts a `momentTimezone` option so I am not sure how this was working for you, unless it was just falling back to a standard `moment` instance.

**Comment by bradyemerson** [comment]
Hmm very odd, not sure how it was working, but none the less, I think it would be helpful in the documentation to explain that the variable either needs to be named moment or passed as a property named moment.  If you agree, I can make that update

**Pull request closed without merging**
