### PR TITLE
Allow target date pattern in input, no longer strip argument quotes

### PR DESCRIPTION
**Pull request by brockpetrie**
Changing how we're handling arguments (not stripping quotes anymore) to mesh with Vue's 1.0.0 changes technically makes this a breaking release. With that said, what do you think about this new parsing method @BrockReece ? Care to help test this?

Basically, trying to allow for the use case at <http://momentjs.com/docs/#/parsing/string-format/> via:

```html
<span>{{ [ someDate, "MM.DD.YY" ] | moment "dddd, MMMM Do YYYY" }}</span>
<!-- or when you want to parse against more than one pattern -->
<span>{{ [ someDate, ["MM.DD.YY", "MM-DD-YY", "MM-DD-YYYY"] ] | moment "dddd, MMMM Do YYYY" }}</span>
```

My first thought was to just do this via another filter arg (e.g. `myDate | moment "MM.DD.YY" "MMMM Do YYYY`) but it definitely adds some overhead. I also kind of like the paradigm of everything left of the pipe being related to parsing of the date, and everything on the right of the pipe being for manipulating and displaying the date.

My favorite solution would be to allow for `myDate, "MM.DD.YY" | moment "dddd, MMMM Do YYYY" ` but it doesn't work with Vue and it's a bit too unconventional. So, just ended up wrapping them in brackets as a proper array.

### CODE REVIEW

**Comment by brockpetrie** [comment]
Also @BrockReece, how should we handle explicitly declaring our Vue version compatibility? Added it as a peer dependency to package.json, but curious what you think.

**Comment by BrockReece** [comment]
Hi Brock,

Sorry for the late reply, it's been a busy week.
It all looks good to me, but I will install your branch on my staging servers later today and test.

Am I right in presuming that propper date objects can be passed per the old syntax?
```js
<span>{{ dateObj | moment "dddd, MMMM Do YYYY" }}</span>
```
  
Also, I've never used peer-dependancy before on any of my packages but your application of it totally makes sense.

A little off topic but have you seen the changes due to be made in V2? Last I heard they were doing away with filters.

Cheers

**Comment by brockpetrie** [comment]
Yep, that's correct. You can still pass a Date obj and Moment will be happy. Or, you can still pass an ISOdate string and Moment will be happy.

And wow, I hadn't heard that! I'm guessing they want to do away with handling this sort of logic in the views?

**Comment by brockpetrie** [comment]
Just checked on the filter implementation in Vue 2.0, and looks like we're good. Filters will only be allowed in within text interpolations, which is how I'm sure most people are using vue-moment anyway. We will have to change the syntax a bit, to something more akin to traditional js like `{{ someDate | moment("dddd, MMMM Do YYYY") }}.

**Pull request merged**
