### PR TITLE
4.0.0

### PR DESCRIPTION
**Pull request by brockpetrie**
- [x] Add linter and get code in adherence to Airbnb styleguide (#60)
- [x] Add `UTC` filter function (#62)
- [x] Add `Duration` filter (#67)
- [x] Support passing options to `calendar` filter function (#60)
- [x] Smarter treatment of numeric inputs: determine if number is in seconds or milliseconds (#69)

### CODE REVIEW

**Comment by BrockReece** [comment]
Do you want me to pick up any of these?

**Comment by brockpetrie** [comment]
I actually have them all done locally, just need to do some final cleanup and add a couple tests!

**Comment by AustinPaquette** [comment]
Anything that can be done to help this along? Really looking forward to the UTC filter function in particular, happy to help however needed. @brockpetrie

**Comment by blackst0ne** [comment]
Any update on this?
Waiting for `4.0.0` because of the `.utc()` support.

**Comment by brockpetrie** [comment]
Sorry everyone! Work has been a bit nutty, but finally have some time to (hopefully) wrap this up this weekend.

Remaining tasks are testing the new Durations PR (#67), testing the 4.0.0 branch as it currently stands, writing a few additional tests, and adding the documentation for #60 to the readme.

**Comment by brockpetrie** [comment]
Alright I think this is ready to go. Could do with a bit of additional testing though!

**Comment by BrockReece** [comment]
Sorry Brock, I didn't have much chance to look at this over the weekend, I will have a good look this morning.

Would you like me to write some additional unit tests if I notice a gap in the coverage?

**Comment by molerat619** [comment]
Hey, when will this be available? I would love to use these features :)

**Comment by rlightner** [comment]
Any idea when you'll actually get this merged in?

**Comment by coxta** [comment]
Let's get this merged!!!

**Comment by BrockReece** [comment]
@brockpetrie
I have taken the liberty of publishing a prerelease for this.
v4.0.0-0 is now be available on NPM

**Comment by blackst0ne** [comment]
What's the problem to release `4.0`?

**Comment by purplelady105** [comment]
Do we have an ETA on releasing `4.0.0`?

**Comment by BrockReece** [comment]
I think we were trying to get some time to properly test this. I have published a prerelease on to NPM a couple of weeks back, is anyone using it that wouldn't mind giving us some real world feedback.

I have loaded it into this [sandbox](https://codesandbox.io/s/k9v3qjvq73) if anyone wants to have a look.

**Comment by scherii** [comment]
I've been using the NPM pre-release since the beginning, it works flawlessly. Before, I used this PR manually, which works without problems. Thank you very much for your work, it is highly appreciated!

**Comment by blackst0ne** [comment]
@BrockReece we've been using the pre-release 4.0 version for a while. 
No problem has been raised.

**Comment by brockpetrie** [comment]
@BrockReece Definitely! Looks like we have some [hopefully] minor conflicts, but I'll leave you to it! Thanks dude

**Comment by BrockReece** [comment]
I have resolved these, it might be worth considering something like #87 so we don't break IE support for our existing users though?

**Comment by BrockReece** [comment]
Merged into master and published v4.0.0

**Comment by AustinPaquette** [comment]
You're my hero for this week.

**Pull request merged**
